### ISSUE TITLE
Don't understand what this script really does?

### ISSUE THREAD

**Issue by xuanngo2001** [donmaiq/unseen-playlistmaker#2]
```
mpv *
# Mark current playing file as seen.
# Quit mpv
mpv *
# mpv still start from the beginning.
```
It is good that this script marks file as seen but then what is next?

**Comment by jonniek** [comment]
mpv * will function normally. This script only loads files from the directory specified in settings. You can activate the script with keybind which will load all the unseen files from the directory you specified. So an example would be:

edit path in settings variable in unseen-playlistmaker.lua
```lua
  unseen_directory = "/home/anon/Videos/",
```
add keybind to input.conf
```
  #toggles playlistmode for unseen-playlistmaker
  W script-message unseenplaylist activate
```
or add a .bashrc alias
```
#starts mpv and loads unseen files
alias mpvw="mpv --script-opts=unseenplayliststart=true --idle"
```
How to use
```
mpv --idle=once
#Key to activate(W or whatever you specified)
#mpv loads all unseen files to playlist from Videos directory
#watch 2 files
#Quit
#repeat above or if you added alias then
mpvw
#loads files right away wihthout activate keybind
#the 2 files watched earlier will not be loaded
```

So you need to specify which directory is the one this script operates on, and even then you will need to activate the script to load files, but marking will still happen automatically even if files are loaded in other ways. On default there will be no key bound to activate so you need to add it to input.conf or pass script opt on startup to activate the script.
